(10/n - non-xlformers conda-on-mast mvp)(monarch-fb/BUCK) Include torchx-fb as part of monarch.whl (#439)
Summary:
Pull Request resolved: https://github.com/pytorch-labs/monarch/pull/439

Includes torchx_fb in `//monarch/python/monarch:monarch.whl` so that `monarch.tools.*` module (uses torchx programmatically) works.

NOTE: Currently fails with  `AttributeError: type object '_asyncio.Task' has no attribute '_step'` (full stacktrace: P1864708102)

## Repro Instructions:

1. Activate `xlformers_finetune_conda:stable`
    ```
    $HOME/fbsource/genai/xlformers/dev/xl_conda.sh xlformers_finetune_conda:stable
    ```

2. Build and install `monarch.whl`
    ```
    $ cd ~/fbsource/fbcode

    $ pip install --force-reinstall --no-deps $(buck build @//mode/opt --show-full-simple-output --config monarch_whl.include=torchx //monarch/python/monarch:monarch.whl)
    ```
3. Run the script (should fail with P1864708102)
    ```
    $ cd ~/fbsource/fbcode/scripts/kiuk/examples/monarch_conda
    $ python main.py
    ```

Reviewed By: highker

Differential Revision: D77411375